#travis configuration for coverage testing
language: c


install:
- cd ${TRAVIS_BUILD_DIR}


# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - make && ./test.out


after_success:
- cd ${TRAVIS_BUILD_DIR}

